### PR TITLE
Update slurm to 17.02.9

### PR DESCRIPTION
**Pull request by uvNikita**

### CODE REVIEW

**Comment by Falkor** [comment]
Actually, I'll even directly target 17.11, once a couple of patch would have passed.

**Comment by uvNikita** [comment]
Sure, it probably makes sense since `17.11` will be released soon in any case. I made this PR just because `17.02.7` version is not available from the default download url: https://download.schedmd.com/slurm and therefore module fails with the default parameters.

**Comment by Falkor** [comment]
Indeed, old versions are stored in a different url than the current one -- that's why I made a `Boolean $src_archived` parameter (set to false by default)-- see [`manifests/download.pp#L21`](https://github.com/ULHPC/puppet-slurm/blob/devel/manifests/download.pp#L21) and [`manifests/download.pp#L75`](https://github.com/ULHPC/puppet-slurm/blob/devel/manifests/download.pp#L75)

**Comment by uvNikita** [comment]
OK, thanks for pointing this out. I'll close this PR then.

**Pull request closed without merging**
