### PR TITLE
Optionally install build dependencies and MySQL

### PR DESCRIPTION
**Pull request by gfa**
Hello

I've used your Puppet module (thanks!) to bootstrap my Slurm cluster, in order to do so I have forked it and made some changes. I'll be sending PRs covering those changes

I don't deploy MySQL (it is managed by another team) nor build slurm on the nodes, this PR addresses those 2 differences. The default action remains the same, install MySQL and build Slurm

Let me know if you prefer smashed or individual commits

### CODE REVIEW

**Comment by Falkor** [comment]
That's fine like that. 
I'm still hesitating to promote that immediately or for the next minor release (current default).

**Comment by runejuhl** [comment]
Hi,

This PR seems to introduce a circular dependency which causes errors if running Puppetserver with `strict_variables = true`. I've patched it in https://github.com/runejuhl/puppet-slurm/commit/80aa55952fec12fc9c1d992d3eab5dad96bcd6c8 ; let me know if you want me to raise a PR.

**Comment by gfa** [comment]
Hi

I no longer use this module, neither have access to test it. 
If I would do this PR again I'll lookup the values of $munge_extra_packages and 
$pre_requisite_packages from hiera, if not declared in hiera set the default values in the module.

**Comment by runejuhl** [comment]
Hi @gfa 

Yes, I'd prefer Hiera too; much nicer for such things. I'll raise another PR with your changes and mine.

**Comment by Falkor** [comment]
From the discussion, I'll close this pull request without merging then. Thanks @gfa nevertheless for the effort.

**Pull request closed without merging**
