### PR TITLE
Add Puppet types, LogTimeFormat parameter

### PR DESCRIPTION
**Pull request by runejuhl**
This PR adds some Slurm-specific Puppet types and makes a few other parameters have more strict types. Also adds `LogTimeFormat` parameter.

### CODE REVIEW

**Comment by Rovanion** [comment]
This pull request has conflicts which need to be resolved. They are probably best fixed by you rebasing your branch runejuhl:add-types onto ULHPC:devel.

https://git-scm.com/docs/git-rebase

**Comment by Rovanion** [comment]
This pull request has conflicts which need to be resolved. They are probably best fixed by you rebasing your branch runejuhl:add-types onto ULHPC:devel.

https://git-scm.com/docs/git-rebase

**Comment by runejuhl** [comment]
Should be good now, thanks for the mention @Rovanion

**Comment by Falkor** [comment]
Sorry, I'll have to close this PR as it's based on outdated code. 
If you're still interested to add the support for LogTimeFormat, kindly reopen one based on the latest version of this module.

**Pull request closed without merging**
